
drawTracks: drawTracks.o Xbulletin.o Xlist.o Xpush.o Xstring.o Xtoggle.o
	cc -o drawTracks drawTracks.o \
	Xbulletin.o Xlist.o Xpush.o Xstring.o Xtoggle.o \
	-lXm -lXt -lX11  -limage

clean:
	rm *.o

